-- MySQL Script generated by MySQL Workbench
-- 10/16/17 15:15:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema jimegaraidsas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jimegaraidsas` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `jimegaraidsas` ;

-- -----------------------------------------------------
-- Table `jimegaraidsas`.`jilog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jimegaraidsas`.`jilog` ;

CREATE TABLE IF NOT EXISTS `jimegaraidsas`.`jilog` (
  `jiid` INT NOT NULL AUTO_INCREMENT,
  `jidate` DATETIME NULL,
  PRIMARY KEY (`jiid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jimegaraidsas`.`rawcontroller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jimegaraidsas`.`rawcontroller` ;

CREATE TABLE IF NOT EXISTS `jimegaraidsas`.`rawcontroller` (
  `jilog_jiid` INT NOT NULL,
  `t1` VARCHAR(45) NULL,
  `t2` VARCHAR(45) NULL,
  `t3` VARCHAR(45) NULL,
  `t4` VARCHAR(45) NULL,
  `t5` VARCHAR(45) NULL,
  `t6` VARCHAR(45) NULL,
  CONSTRAINT `fk_rawcontroller_jilog`
    FOREIGN KEY (`jilog_jiid`)
    REFERENCES `jimegaraidsas`.`jilog` (`jiid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jimegaraidsas`.`rawhd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jimegaraidsas`.`rawhd` ;

CREATE TABLE IF NOT EXISTS `jimegaraidsas`.`rawhd` (
  `jilog_jiid` INT NOT NULL,
  `t1` VARCHAR(45) NULL,
  `t2` VARCHAR(45) NULL,
  CONSTRAINT `fk_table1_jilog1`
    FOREIGN KEY (`jilog_jiid`)
    REFERENCES `jimegaraidsas`.`jilog` (`jiid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jimegaraidsas`.`rawconfig`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jimegaraidsas`.`rawconfig` ;

CREATE TABLE IF NOT EXISTS `jimegaraidsas`.`rawconfig` (
  `jilog_jiid` INT NOT NULL,
  `t1` VARCHAR(50) NULL,
  CONSTRAINT `fk_table2_jilog1`
    FOREIGN KEY (`jilog_jiid`)
    REFERENCES `jimegaraidsas`.`jilog` (`jiid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
